"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FileText } from "lucide-react";

interface ComplianceReportProps {
  markdown: string | null;
  complianceView?: boolean;
  legalName?: string;
  companyToken?: string;
}

interface ReportSection {
  title: string | null;
  lines: string[];
}

function splitReportSections(text: string): ReportSection[] {
  const sections: ReportSection[] = [];
  let current: ReportSection = { title: null, lines: [] };

  for (const line of text.split("\n")) {
    if (line.startsWith("## ")) {
      if (current.title || current.lines.some((item) => item.trim())) {
        sections.push(current);
      }
      current = { title: line.slice(3), lines: [] };
      continue;
    }
    current.lines.push(line);
  }

  if (current.title || current.lines.some((item) => item.trim())) {
    sections.push(current);
  }
  return sections;
}

/** Minimal Markdown renderer: bold, headers, horizontal rules, bullet lists. */
function renderMarkdown(text: string): React.ReactNode[] {
  return text.split("\n").map((line, i) => {
    if (line.startsWith("# ")) {
      return (
        <h3
          key={i}
          className="mt-6 first:mt-0 text-xl font-bold text-slate-100 tracking-tight"
        >
          {line.slice(2)}
        </h3>
      );
    }
    if (line.startsWith("## ")) {
      return (
        <h4
          key={i}
          className="mt-5 text-sm font-semibold text-slate-300 uppercase tracking-widest"
        >
          {line.slice(3)}
        </h4>
      );
    }
    if (line.startsWith("---")) {
      return <hr key={i} className="my-4 border-slate-800" />;
    }
    if (line.startsWith("- ")) {
      return (
        <li key={i} className="ml-5 text-sm text-slate-300 list-disc leading-relaxed">
          {parseBold(line.slice(2))}
        </li>
      );
    }
    if (line.includes("**")) {
      return (
        <p key={i} className="text-sm text-slate-300 leading-relaxed">
          {parseBold(line)}
        </p>
      );
    }
    if (line.trim() === "") return <div key={i} className="h-2" />;
    return (
      <p key={i} className="text-sm text-slate-300 leading-relaxed">
        {line}
      </p>
    );
  });
}

function parseBold(text: string): React.ReactNode {
  const parts = text.split(/\*\*(.*?)\*\*/g);
  return parts.map((part, i) =>
    i % 2 === 1 ? (
      <strong key={i} className="font-semibold text-slate-100">
        {part}
      </strong>
    ) : (
      part
    )
  );
}

export function ComplianceReport({
  markdown,
  complianceView = false,
  legalName,
  companyToken,
}: ComplianceReportProps) {
  let displayMarkdown = markdown;
  if (complianceView && markdown && legalName) {
    displayMarkdown = markdown.split(legalName).join(companyToken || "MASKED_COMPANY_001");
  }
  const sections = displayMarkdown ? splitReportSections(displayMarkdown) : [];
  const intro = sections[0]?.title ? null : sections[0] ?? null;
  const bodySections = intro ? sections.slice(1) : sections;

  return (
    <Card className="border-slate-800 bg-slate-900 shadow-none w-full">
      <CardHeader className="border-b border-slate-800 px-6 py-4">
        <CardTitle className="flex flex-wrap items-center gap-2.5 text-base font-semibold text-slate-200">
          <FileText className="h-4 w-4 text-slate-500" strokeWidth={1.75} />
          Agent Forensic Report
          <span className="text-xs font-normal text-slate-500">
            Generated by AMINA Bank pKYC Engine
          </span>
        </CardTitle>
      </CardHeader>
      <CardContent className="px-6 py-5">
        {markdown ? (
          <div className="space-y-5">
            {intro && (
              <div className="rounded-lg border border-slate-800 bg-slate-950 px-5 py-4">
                <div className="max-w-5xl space-y-1">
                  {renderMarkdown(intro.lines.join("\n"))}
                </div>
              </div>
            )}
            <div className="grid gap-4 xl:grid-cols-2">
              {bodySections.map((section, index) => (
                <section
                  key={`${section.title ?? "section"}-${index}`}
                  className="rounded-lg border border-slate-800 bg-slate-950 px-5 py-4"
                >
                  {section.title && (
                    <h4 className="mb-3 text-sm font-semibold uppercase tracking-widest text-slate-300">
                      {section.title}
                    </h4>
                  )}
                  <div className="space-y-1">
                    {renderMarkdown(section.lines.join("\n"))}
                  </div>
                </section>
              ))}
            </div>
          </div>
        ) : (
          <div className="flex flex-col items-center gap-3 py-14 text-slate-600">
            <FileText className="h-10 w-10 opacity-25" />
            <p className="text-base font-medium text-slate-500">Report not generated</p>
            <p className="text-sm text-slate-600">
              Forensic reports are produced only when the combined risk score
              exceeds the alarm threshold.
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
