"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FileText } from "lucide-react";

interface ComplianceReportProps {
  markdown: string | null;
}

/** Minimal Markdown renderer — bold, headers, horizontal rules, bullet lists */
function renderMarkdown(text: string): React.ReactNode[] {
  return text.split("\n").map((line, i) => {
    if (line.startsWith("# ")) {
      return (
        <h3
          key={i}
          className="mt-6 first:mt-0 text-xl font-bold text-slate-100 tracking-tight"
        >
          {line.slice(2)}
        </h3>
      );
    }
    if (line.startsWith("## ")) {
      return (
        <h4
          key={i}
          className="mt-5 text-sm font-semibold text-slate-300 uppercase tracking-widest"
        >
          {line.slice(3)}
        </h4>
      );
    }
    if (line.startsWith("---")) {
      return <hr key={i} className="my-4 border-slate-800" />;
    }
    if (line.startsWith("- ")) {
      return (
        <li key={i} className="ml-5 text-base text-slate-300 list-disc leading-relaxed">
          {parseBold(line.slice(2))}
        </li>
      );
    }
    if (line.includes("**")) {
      return (
        <p key={i} className="text-base text-slate-300 leading-relaxed">
          {parseBold(line)}
        </p>
      );
    }
    if (line.trim() === "") return <div key={i} className="h-2" />;
    return (
      <p key={i} className="text-base text-slate-300 leading-relaxed">
        {line}
      </p>
    );
  });
}

function parseBold(text: string): React.ReactNode {
  const parts = text.split(/\*\*(.*?)\*\*/g);
  return parts.map((part, i) =>
    i % 2 === 1 ? (
      <strong key={i} className="font-semibold text-slate-100">
        {part}
      </strong>
    ) : (
      part
    )
  );
}

export function ComplianceReport({ markdown }: ComplianceReportProps) {
  return (
    <Card className="border-slate-800 bg-slate-900 shadow-none w-full">
      <CardHeader className="border-b border-slate-800 px-6 py-4">
        <CardTitle className="flex items-center gap-2.5 text-base font-semibold text-slate-200">
          <FileText className="h-4 w-4 text-slate-500" strokeWidth={1.75} />
          Agent Forensic Report
          <span className="ml-1 text-xs font-normal text-slate-500">
            Generated by AMINA Bank pKYC Engine
          </span>
        </CardTitle>
      </CardHeader>
      <CardContent className="px-8 py-6">
        {markdown ? (
          <div className="space-y-1 max-w-4xl">{renderMarkdown(markdown)}</div>
        ) : (
          <div className="flex flex-col items-center gap-3 py-14 text-slate-600">
            <FileText className="h-10 w-10 opacity-25" />
            <p className="text-base font-medium text-slate-500">Report not generated</p>
            <p className="text-sm text-slate-600">
              Forensic reports are produced only when the combined risk score
              exceeds the alarm threshold.
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
